import vehicle
import surmotors_sale_order
import surmotors_res_partner
import surmotors_fleet_vehicle
import surmotors_fleet_vehicle_log_contract
import surmotors_hr_employee
import surmotors_fleet_vehicle_cost_tipo
import surmotors_bahias
import surmotors_production
import product
# import surmotors_fleet_vehicle_product
